/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#006e4b",
        "primary": "#3525cd",
        "secondary-container": "#fea619",
        "tertiary-fixed": "#6ffbbe",
        "surface-dim": "#d9dadc",
        "primary-container": "#4f46e5",
        "inverse-primary": "#c3c0ff",
        "surface-container-high": "#e7e8ea",
        "tertiary": "#005338",
        "primary-fixed": "#e2dfff",
        "secondary": "#855300",
        "secondary-fixed": "#ffddb8",
        "on-tertiary": "#ffffff",
        "surface-container": "#edeef0",
        "on-surface": "#191c1e",
        "outline-variant": "#c7c4d8",
        "on-secondary": "#ffffff",
        "on-primary-container": "#dad7ff",
        "surface-variant": "#e1e2e4",
        "surface-bright": "#f8f9fb",
        "primary-fixed-dim": "#c3c0ff",
        "on-background": "#191c1e",
        "on-primary": "#ffffff",
        "outline": "#777587",
        "on-surface-variant": "#464555",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "inverse-surface": "#2e3132",
        "surface-container-low": "#f2f4f6",
        "surface-tint": "#4d44e3",
        "on-secondary-container": "#684000",
        "on-tertiary-fixed": "#002113",
        "surface-container-highest": "#e1e2e4",
        "on-tertiary-container": "#67f4b7",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#653e00",
        "inverse-on-surface": "#f0f1f3",
        "surface": "#f8f9fb",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#ffb95f",
        "on-primary-fixed-variant": "#3323cc",
        "on-primary-fixed": "#0f0069",
        "on-secondary-fixed": "#2a1700",
        "on-tertiary-fixed-variant": "#005236",
        "tertiary-fixed-dim": "#4edea3",
        "background": "#f8f9fb"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin_mobile": "16px",
        "sidebar_width": "240px",
        "gutter": "24px",
        "topbar_height": "64px",
        "container_max_width": "1200px",
        "margin_desktop": "40px"
      },
      fontFamily: {
        "label-md": ["Inter"],
        "body-md": ["Inter"],
        "headline-md": ["Inter"],
        "headline-sm": ["Inter"],
        "headline-xl-mobile": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-lg": ["Inter"],
        "body-sm": ["Inter"],
        "headline-xl": ["Inter"]
      },
      fontSize: {
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-xl-mobile": ["32px", { lineHeight: "40px", fontWeight: "800" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "800" }]
      }
    },
  },
  plugins: [],
};
